services:
  # The gateway server runs in stdio mode and launches backend processes
  # It should be configured directly in your MCP client (e.g., Claude Desktop)
  # 
  # Example Claude Desktop configuration:
  # {
  #   "mcpServers": {
  #     "mcpware": {
  #       "command": "docker",
  #       "args": ["compose", "run", "--rm", "mcpware"],
  #       "env": {
  #         "GITHUB_PERSONAL_ACCESS_TOKEN": "<YOUR_TOKEN>"
  #       }
  #     }
  #   }
  # }
  
  mcpware:
    build: .
    image: mcpware-gateway
    volumes:
      - ./config.json:/app/config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Mount Docker socket for Docker-in-Docker
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN
    stdin_open: true
    tty: true
    # For backends that need network access
    network_mode: host 